---

- name: "DEPLOY --> PROXY SERVERS"
  hosts: proxy_srv
  roles:
    - { role: klems.packages-installer, sys_packages: ['nginx', 'certbot']}
    - setup.letsencrypt-web-certificates
    - setup.nginx-proxy
