---

- src: https://github.com/klems/ansible-role-sysadmin-tools
  version: fef433e70fe8ef57f3e9da3a903f1a05c1539231
  name: klems.sysadmin-tools

- src: https://github.com/klems/ansible-role-locales-timezone
  version: 1253c658aa9cd72d7d13ecfff876c6b68402de07
  name: klems.locales-timezone

- src: https://github.com/klems/ansible-role-motd
  version: 92fce79c67ab4a35206a9ba62ecd86bfef45b0e7
  name: klems.motd

- src: https://github.com/klems/ansible-role-partition-and-mount-disks
  version: b5f870de352af7754d3eb7a63b9a94d322398959
  name: klems.partition-and-mount-disks

- src: https://github.com/klems/ansible-role-install-resilio
  version: 310d10b43e91ea42548a2c0fe33ab90c97fb8ddf
  name: klems.install-resilio

- src: https://github.com/klems/ansible-role-crontabs
  version: 0124a16af167354dc74d877f303c201bcd12c5e0
  name: klems.crontabs
