---

- name: "updating hostname ..."
  hostname:
    name: "{{ hostname }}"
  become: yes

- name: "removing 'raspberrypi' from [/etc/hosts] ..."
  replace:
    dest: /etc/hosts
    regexp: 'raspberrypi'
    replace: "{{ hostname}}"
    backup: yes
  become: yes

- name: "adding DNS entry in [/etc/hosts] ..."
  lineinfile:
    dest: "/etc/hosts"
    line: "{{ ansible_eth0.ipv4.address }} {{ hostname }}"
  when: ansible_eth0.ipv4.address is defined
  become: yes
