---

- name: "adding FQDN to /etc/hosts"
  lineinfile:
    path: /etc/hosts
    line: "127.0.1.1 {{ ansible_nodename }} {{ ansible_nodename }}.{{ domain }}"
    regexp: "^127.0.1.1.*$"
  become: yes

- name: "adding dns entries for every pi ..."
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  with_items: "{{ dns_entries }}"
  become: yes
