---

- name: update db aliases
  command: postalias /etc/aliases
  become: yes

- name: restart postfix
  service:
    name: postfix
    state: restarted
    enabled: yes
  become: yes

- name: restart dovecot
  service:
    name: dovecot
    state: restarted
    enabled: yes
  become: yes
