---

- name: restart nginx
  service:
    name=nginx
    state=restarted
    enabled=yes
  become: yes

- name: restart php7-fpm
  service:
    name=php7.0-fpm
    state=restarted
    enabled=yes
  become: yes
